############## WJetsToLNu ##############
WtoLNu_amcatnloFXFX:
  sampleType: W


############## TT ##############
TT:
  sampleType: TT
TTto2L2Nu:
  sampleType: TT
TTto4Q:
  sampleType: TT
TTtoLNu2Q:
  sampleType: TT
#Sometimes the 'To' is 'to'
#This took like 3 hours of my life away ):
TTto2L2Nu:
  sampleType: TT
TTto4Q:
  sampleType: TT
TTtoLNu2Q:
  sampleType: TT


############## DY ##############
DYto2L_M_10to50_amcatnloFXFX:
  sampleType: DY
DYto2L_M_50_amcatnloFXFX:
  sampleType: DY

############## EWK ##############


############## single Higgs ##############


############## VH non-inclusive ##############


############## VV inclusive ##############
WW:
  sampleType: VV
WZ:
  sampleType: VV
ZZ:
  sampleType: VV


############## VVV inclusive ##############


############## ST #############
ST_s_channel_antitop_4f_leptonDecays:
  sampleType: ST
ST_s_channel_top_4f_leptonDecays:
  sampleType: ST
ST_t_channel_antitop_4f_InclusiveDecays:
  sampleType: ST
ST_t_channel_top_4f_InclusiveDecay:
  sampleType: ST
ST_tW_antitop_2L2Nu:
  sampleType: ST
ST_tW_antitop_4Q:
  sampleType: ST
ST_tW_antitop_LNu2Q:
  sampleType: ST
ST_tW_top_2L2Nu:
  sampleType: ST
ST_tW_top_4Q:
  sampleType: ST
ST_tW_top_LNu2Q:
  sampleType: ST

############## TTX inclusive ##############
TTWW:
  sampleType: TTX
TTWH:
  sampleType: TTX
TTZH:
  sampleType: TTX
TTZToQQ:
  sampleType: TTX
TTZZ:
  sampleType: TTX


############## ttH ##############


