#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=.github/scripts/ci/common.sh
source "${SCRIPT_DIR}/common.sh"

require_var ANALYSIS_NAME
require_var ANALYSIS_TASK
require_var ANALYSIS_ARGS
require_var ERA

LAW_WORKERS="${LAW_WORKERS:-4}"

init_env
init_ssh
init_voms
init_gfal

extract_build_archive "${ANALYSIS_NAME}"

# Outputs of the previous stages (staged from GitHub artifacts) are laid out relative to
# FLAF_CI_ROOT, so they land exactly where the tasks of this stage expect their inputs.
if [[ -d ${STAGE_INPUTS_DIR} ]]; then
  echo "Restoring outputs of the previous stage from ${STAGE_INPUTS_DIR}..."
  cp -a "${STAGE_INPUTS_DIR}/." "${FLAF_CI_ROOT}/"
fi

cd "${FLAF_CI_ROOT}/${ANALYSIS_NAME}"

# The environment was installed once by the build job and travels in the build archive.
# FLAF_NO_INSTALL makes env.sh fail loudly if anything is missing instead of silently
# re-installing flaf_env/CMSSW/combine in every test job (~20 min each).
export FLAF_NO_INSTALL=1
source_analysis_env
init_voms

# ci_custom.yaml pins fs_default to the job directory of the GitLab CI, which does not
# exist on GitHub runners. Redirect the CI output area to the shared build volume so
# that it survives the container and can be handed to the next stage as an artifact.
CI_OUTPUT_DIR="${FLAF_CI_ROOT}/output/${ANALYSIS_NAME}"
GHA_CUSTOM_CONFIG="${FLAF_CI_ROOT}/gha_custom.yaml"
cat << EOF > "${GHA_CUSTOM_CONFIG}"
# Generated by .github/scripts/ci/test_analysis.sh
fs_default:
  - ${CI_OUTPUT_DIR}
EOF
mkdir -p "${CI_OUTPUT_DIR}"

echo "Running task: ${ANALYSIS_TASK} ${ANALYSIS_ARGS} for era: ${ERA}"
# shellcheck disable=SC2086
law run "${ANALYSIS_TASK}" --version CI --period "${ERA}" --workflow local \
  --workers "${LAW_WORKERS}" --user-custom "${GHA_CUSTOM_CONFIG}" ${ANALYSIS_ARGS}

echo "=== Task ${ANALYSIS_TASK} (${ERA}) completed successfully ==="
