name: Checkout FLAF submodule
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Fetch FLAF submodule
      if: ${{ github.repository != 'cms-flaf/FLAF' }}
      shell: bash
      run: |
        echo "Repository: ${{ github.repository }}"
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule update --init FLAF
        cd FLAF
        git checkout main
