- name: QCD
  types:
    - QCD
  title: QCD
  color: kOrange-3
- name: DY
  types:
    - DY
  title: "DY Z#rightarrow ll + jets"
  color: kAzure+10
- name: TT
  types:
    - TT
  title: t#bar{t}
  color: kGreen+3
  # color: kGreen-4
- name: W
  title: W+Jets
  types:
    - W
  color: kPink+1
- name: ST
  types:
    - ST
  title: Single top
  color: kCyan
- name: single_H
  title: H
  types:
    - ttH
    - VH
    - H
  color: kYellow
- name: VV
  types:
    - VV
  title: VV
  color: kViolet+8
- name: VVV
  types:
    - VVV
  title: VVV
  color: kBlue-9
- name: EWK
  title: "EWK"
  types:
    - EWK
  color: kYellow+2
- name: Other
  title: "TTX"
  types: []
  color: kRed-7 #kCyan+4
- name: GluGluToBulkGraviton_1250
  title: "GGBG-1250"
  type: signal
  types:
   - GluGluToBulkGraviton
  color: kCyan
  #scale: 0.05
- name: GluGluToRadion_1250
  title: "GGR-1250"
  type: signal
  types:
   - GluGluToRadion
  color: kRed
- name: GluGluToRadion_700
  title: "GGR-700"
  type: signal
  types:
   - GluGluToRadion
  color: kYellow
- name: GluGluToRadion_450
  title: "GGR-450"
  type: signal
  types:
   - GluGluToRadion
  color: kGreen
- name: data
  title: "data obs"
  types:
    - data
  type: data
#- name: W
  #types:
  #  - W
  #title: "W #rightarrow l#nu + jets"
  #color: kYellow-7