era: Run3_2026
luminosity: 27987  # pb-1, approximate (110:111:28 of 2024:2025:2026)
# Same Summer24 MC as 2024. Some 2026 corrections are not yet available.
# shared_mc is inherited from reuse_mc_from_era.
reuse_mc_from_era: Run3_2024
weight_base_branch: weight_base
nano_version: v15
crossSectionsFile: FLAF/config/crossSections13p6TeV.yaml
MET_flags:  # https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#Run_3_2024_data_and_MC_Recommend
  - Flag_goodVertices
  - Flag_globalSuperTightHalo2016Filter
  - Flag_EcalDeadCellTriggerPrimitiveFilter
  - Flag_BadPFMuonFilter
  - Flag_BadPFMuonDzFilter
  - Flag_hfNoisyHitsFilter
  - Flag_eeBadScFilter
  - Flag_ecalBadCalibFilter
# lumiFile: 2026 golden JSON not yet available
