# no MC for 2025:
# ^(A-Z)*.:
#   - Run3_2025
# DY
^DYto2(E|Mu|Tau)_M_50_[012]J_amcatnloFXFX:
  - Run3_2025
^DYto2(E|Mu|Tau)_M_(10to50|50)_amcatnloFXFX:
  - Run3_2025
^DYto2(E|Mu|Tau)_MLL_*.:
  - Run3_2025
^DYto2L_M_50_PTLL_*.:
  - Run3_2025
^DYto2L_M_(10to50|50)_amcatnloFXFX:
  - Run3_2024
  - Run3_2025
^DYto2L_M_50_[012]J_amcatnloFXFX:
  - Run3_2024
  - Run3_2025
^DYto2(E|Mu)_M_50_PTLL_.*_amcatnloFXFX:
  - Run3_2024
  - Run3_2025
^DYto2.*_M_50_amcatnloFXFX_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
^DYto2Tau_M_50_(0|1|2)J_Filtered_amcatnloFXFX:
  - Run3_2024
  - Run3_2025
# H
^GluGluH*.:
  - Run3_2025
GluGluHto2B_M125_ext1:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
GluGluHto2Tau_M125:
  - Run3_2022EE
  - Run3_2023
^ggZH_.*:
  - Run3_2025
^ggZH_.*_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
^GluGlutoContinto.*:
  - Run3_2022
  - Run3_2024
GluGlutoContinto2Zto2Mu2Tau:
  - Run3_2023
^VBFH*.:
  - Run3_2025
VBFHto2B_M125_ext1:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
# VH
^W(minus|plus)H_Hto2B_.*_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
^ZH.*:
  - Run3_2025
^ZH_Hto2B.*_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
^W(plus|minus)H_Hto2B_Wto2Q$:
  - Run3_2024

# QCD
QCD_HT40to70_MLM:
  - Run3_2022EE
QCD_PT_300toInf_EMEnriched:
  - Run3_2022EE
QCD_PT_300_EMEnriched:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2022
^QCD_PT_.*:
  - Run3_2024
  - Run3_2025
^QCD_HT.*:
  - Run3_2025
# ST
^T(bar|)W.*_ext1:
  - Run3_2023
  - Run3_2023BPix
# TT
TT:
  - Run3_2022EE
  - Run3_2023
  - Run3_2024
  - Run3_2025
TT_ext1:
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
  - Run3_2025
TTto2L2Nu_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
TTto4Q_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
TTtoLNu2Q_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
^TTto(2L2Nu|LNu2Q|4Q):
  - Run3_2025
TTZ_Zto2Q:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2025
TTWZ:
  - Run3_2022
  - Run3_2025
^TTZ(Z|H)_Z(Z|H)to4B:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
  - Run3_2025
TTZZ:
  - Run3_2024
  - Run3_2025
TTZH:
  - Run3_2024
  - Run3_2025

^TT(WH|WW):
  - Run3_2025

^TTHto*:
  - Run3_2025

# VBF
VBFHto2Tau_M125:
  - Run3_2022EE

# W
^W(minus|plus|to)*.:
  - Run3_2025
WtoLNu_madgraphMLM_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
WtoLNu_madgraphMLM:
  - Run3_2024
WtoLNu_amcatnloFXFX:
  - Run3_2024
^WtoLNu_(0|1)J_amcatnloFXFX:
  - Run3_2024
# VV
ZZ:
  - Run3_2025
^ZZto*.:
  - Run3_2025
^WW.*_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
^WZ.*_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
^ZZ.*_ext1:
  - Run3_2023
  - Run3_2023BPix
  - Run3_2024
# VVV
ZZZ:
  - Run3_2025
# change name in W samples..
WtoENu_amcatnloFXFX:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
WtoMuNu_amcatnloFXFX:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
WtoTauNu_amcatnloFXFX:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix

# inclusive and exclusive single top samples
^T(W|bar).*_ext1:
  - Run3_2024
^T(barB|Bbar)Q_t_channel_4FS:
  - Run3_2024
^T(barB|Bbar)Qto(LNu|2Q)_t_channel_4FS:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
  - Run3_2025
^T(barB|Bbar)toL(minus|plus)Nu(B|Bbar)_s_channel_4FS:
  - Run3_2025
^T(barBQ|BbarQ)_t_channel_4FS:
  - Run3_2025

^T(barWplus|Wminus)to(2L2Nu|4Q|LNu2Q):
  - Run3_2025

ZHto2Tau_UncorrelatedDecay_UnFiltered:
  - Run3_2024
^Zto2Q_HT_(400to600|600to800|800toInf|200to400):
  - Run3_2024
  - Run3_2025

^Zto2Q_HT_(100to400|400to800|800to1500|1500to2500|2500toInf):
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
  - Run3_2025

^Zto2Nu_HT*.:
  - Run3_2025
