# https://twiki.cern.ch/twiki/bin/view/CMS/PdmVDataReprocessingUL2016#Run2016F_part2
# extra bits of associated information: 0 => HLT_AK8PFJetX_SoftDropMass40_PFAK8ParticleNetTauTau0p30, 1 => hltAK8SinglePFJets230SoftDropMass40PNetTauTauTag0p03 for BoostedTau;
# 0 => CaloIdL_TrackIdL_IsoVL, 1 => 1e (WPTight), 2 => 1e (WPLoose), 3 => OverlapFilter PFTau, 4 => 2e, 5 => 1e-1mu, 6 => 1e-1tau, 7 => 3e, 8 => 2e-1mu, 9 => 1e-2mu, 10 => 1e (32_L1DoubleEG_AND_L1SingleEGOr), 11 => 1e (CaloIdVT_GsfTrkIdT), 12 => 1e (PFJet), 13 => 1e (Photon175_OR_Photon200) for Electron;
# 0 => , 1 => hltAK8SingleCaloJet200, 2 => , 3 => hltAK8SinglePFJets230SoftDropMass40BTagParticleNetBB0p35 OR hltAK8SinglePFJets250SoftDropMass40BTagParticleNetBB0p35 OR hltAK8SinglePFJets275SoftDropMass40BTagParticleNetBB0p35, 4 => hltAK8DoublePFJetSDModMass30, 5 => hltAK8DoublePFJetSDModMass50 for FatJet;
# 0 => hltL1sTripleJetVBFIorHTTIorDoubleJetCIorSingleJet, 1 => hltL1sQuadJetC50IorQuadJetC60IorHTT280IorHTT300IorHTT320IorTripleJet846848VBFIorTripleJet887256VBFIorTripleJet927664VBF OR hltL1sQuadJetCIorTripleJetVBFIorHTT, 2 => hltL1sQuadJetC60IorHTT380IorHTT280QuadJetIorHTT300QuadJet OR hltL1sQuadJetC50to60IorHTT280to500IorHTT250to340QuadJet, 3 => hltCaloQuadJet30HT300 OR hltCaloQuadJet30HT320, 4 => hltPFCentralJetsLooseIDQuad30HT300 OR hltPFCentralJetsLooseIDQuad30HT330, 5 => hltPFHT280Jet30 for HT;
# 0 => VBF cross-cleaned from loose iso PFTau, 1 => hltBTagCaloCSVp087Triple, 2 => hltDoubleCentralJet90, 3 => hltDoublePFCentralJetLooseID90, 4 => hltL1sTripleJetVBFIorHTTIorDoubleJetCIorSingleJet, 5 => hltQuadCentralJet30, 6 => hltQuadPFCentralJetLooseID30, 7 => hltL1sQuadJetC50IorQuadJetC60IorHTT280IorHTT300IorHTT320IorTripleJet846848VBFIorTripleJet887256VBFIorTripleJet927664VBF or hltL1sQuadJetCIorTripleJetVBFIorHTT, 8 => hltQuadCentralJet45, 9 => hltQuadPFCentralJetLooseID45, 10 => hltL1sQuadJetC60IorHTT380IorHTT280QuadJetIorHTT300QuadJet or hltL1sQuadJetC50to60IorHTT280to500IorHTT250to340QuadJet, 11 => hltBTagCaloCSVp05Double or hltBTagCaloDeepCSVp17Double, 12 => hltPFCentralJetLooseIDQuad30, 13 => hlt1PFCentralJetLooseID75, 14 => hlt2PFCentralJetLooseID60, 15 => hlt3PFCentralJetLooseID45, 16 => hlt4PFCentralJetLooseID40, 17 => hltBTagPFCSVp070Triple or hltBTagPFDeepCSVp24Triple or hltBTagPFDeepCSV4p5Triple, 18 => Double tau + jet, 19 => VBF cross-cleaned from medium deeptau PFTau, 20 => VBF cross-cleaned using dijet correlation checker, 21 => monitoring muon + tau + jet for Jet;
# 0 => hltCaloQuadJet30HT300 OR hltCaloQuadJet30HT320, 1 => hltPFCentralJetsLooseIDQuad30HT300 OR hltPFCentralJetsLooseIDQuad30HT330 for MHT;
# 0 => TrkIsoVVL, 1 => Iso, 2 => OverlapFilter PFTau, 3 => IsoTkMu, 10 => 1mu (Mu50) for Muon;
# 0 => hltEG33L1EG26HEFilter, 1 => hltEG50HEFilter, 2 => hltEG75HEFilter, 3 => hltEG90HEFilter, 4 => hltEG120HEFilter, 5 => hltEG150HEFilter, 6 => hltEG150HEFilter, 7 => hltEG200HEFilter, 8 => hltHtEcal800, 9 => hltEG110EBTightIDTightIsoTrackIsoFilter, 10 => hltEG120EBTightIDTightIsoTrackIsoFilter, 11 => 1mu-1photon, 12 => hltEG30LR9Id85b90eHE12R9Id50b80eR9IdLastFilter, 13 => hltEG30LIso60CaloId15b35eHE12R9Id50b80eEcalIsoLastFilter, 14 => hltEG22Iso60CaloId15b35eHE12R9Id50b80eTrackIsoUnseededLastFilter, 15 => hltEG22R9Id85b90eHE12R9Id50b80eR9UnseededLastFilter, 16 => hltEG30Iso60CaloId15b35eR9Id50b90eHE12b10eR9Id50b80eEcalIsoFilter, 17 => hltEG18TrackIso60Iso60CaloId15b35eR9Id50b90eHE12b10eR9Id50b80eTrackIsoUnseededFilter for Photon;
# 0 => LooseIso, 1 => Medium(Comb)Iso, 2 => VLooseIso, 3 => None, 4 => L2p5 pixel iso, 5 => OverlapFilter IsoMu, 6 => OverlapFilter IsoEle, 7 => L1-HLT matched, 8 => Dz for Tau;

ditau:
  channels:
    - tauTau
  path_data:
    - HLT_DoubleMediumCombinedIsoPFTau35_Trk1_eta2p1_Reg && run >= 278820
    - HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg && run < 278820
  path_MC:
    - HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg
  legs:
    - offline_obj:
        type: Tau
        cut: v_ops::pt(Tau_p4) > 40 && abs(v_ops::eta(Tau_p4)) < 2.1
      online_obj:
        cuts:
          - cut: TrigObj_id==15 && (TrigObj_filterBits&2)!=0 && (TrigObj_filterBits&256)!=0
      doMatching: True
    - ref_leg: 0

singleTau:
  channels:
    - tauTau
    - muTau
    - eTau
  path:
    - HLT_VLooseIsoPFTau120_Trk50_eta2p1
    - HLT_VLooseIsoPFTau140_Trk50_eta2p1
  legs:
    - offline_obj:
        type: Tau
        cut: v_ops::pt(Tau_p4) > 130 && abs(v_ops::eta(Tau_p4)) < 2.1  # for next prod
      online_obj:
        cut: TrigObj_id == 15 && (TrigObj_filterBits&4)!=0
      doMatching: True

singleMu:
  channels:
    - muTau
    - muMu
    - eMu
  path:
    - HLT_IsoMu24
    # - HLT_IsoMu24_eta2p1
    - HLT_IsoTkMu24
    # - HLT_IsoTkMu24_eta2p1
  legs:
    - offline_obj:
        type: Muon
        cut: v_ops::pt(Muon_p4) > 26  # && abs(v_ops::eta(Muon_p4)) < 2.1
      online_obj:
        cut: TrigObj_id == 13 && ((TrigObj_filterBits&2) != 0 || (TrigObj_filterBits&8) != 0 )
      doMatching: True

mutau:
  channels:
    - muTau
  path:
    - HLT_IsoMu19_eta2p1_LooseIsoPFTau20
    - HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1
  legs:
    - offline_obj:
        type: Muon
        cut: v_ops::pt(Muon_p4) > 21 && abs(v_ops::eta(Muon_p4)) < 2.1
      online_obj:
        cut: TrigObj_id==13 && (TrigObj_filterBits&4)!=0 && TrigObj_pt>19
      doMatching: True
    - offline_obj:
        type: Tau
        cut: v_ops::pt(Tau_p4) > 25 && abs(v_ops::eta(Tau_p4)) < 2.1
      online_obj:
        cut: TrigObj_id==15 && (TrigObj_filterBits&32)!=0  && (TrigObj_filterBits&1)!=0
      doMatching: True

MET:
  channels:
    - tauTau
    - muTau
    - eTau
  path:
    - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
  legs:
    - offline_obj:
        type: MET
        cut: metnomu_pt > 130
      doMatching: False

singleEle:
  channels:
    - eTau
    - eE
    - eMu
  path:
    - HLT_Ele25_eta2p1_WPTight_Gsf
    # - HLT_Ele35_WPTight_Gsf ? understand
  legs:
    - offline_obj:
        type: Electron
        cut: v_ops::pt(Electron_p4) > 27 && abs(v_ops::eta(Electron_p4)) < 2.1
      online_obj:
        cut: TrigObj_id == 11 && (TrigObj_filterBits&2)!=0
      doMatching: True

etau:
  channels:
    - eTau
  path_data:
    - HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1 && run < 276215
    - HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20 && 276215 <= run && run < 278270
    - HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30 && run >= 278270
  path_MC:
    - HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1
  legs:
    - offline_obj:
        type: Electron
        cut: v_ops::pt(Electron_p4) > 26 && abs(v_ops::eta(Electron_p4)) < 2.1
      online_obj:
        cut: TrigObj_id==11 && (TrigObj_filterBits&8)!=0 && TrigObj_pt>24
      doMatching: True
    - offline_obj:
        type: Tau
        cut: v_ops::pt(Tau_p4) > 25 && abs(v_ops::eta(Tau_p4)) < 2.1
      online_obj:
        cut: TrigObj_id==15 && (TrigObj_filterBits&64)!=0 && (TrigObj_filterBits&1)!=0
      doMatching: True
